<template><div><h1 id="⛳使用gametest生成空岛" tabindex="-1"><a class="header-anchor" href="#⛳使用gametest生成空岛" aria-hidden="true">#</a> ⛳使用Gametest生成空岛</h1>
<div class="custom-container warning"><p class="custom-container-title">编写中页面提醒</p>
<p>本页面仍处于编写状态中，内容可能不全面，会对阅读造成一定的影响！</p>
</div>
<div class="custom-container warning"><p class="custom-container-title">注意游戏版本</p>
<p>由于Gametest官方的API一直属于测试阶段，可能会随时更改，以下脚本格式仅仅保证在正式版1.19.5上可以正常使用！</p>
</div>
<h3 id="❓什么是gametest" tabindex="-1"><a class="header-anchor" href="#❓什么是gametest" aria-hidden="true">#</a> ❓什么是Gametest？</h3>
<p><a href="https://learn.microsoft.com/zh-cn/minecraft/creator/documents/gametestgettingstarted" target="_blank" rel="noopener noreferrer">Gametest又称为“游戏测试框架”<ExternalLinkIcon/></a>，你可以编写一些简单的 JavaScript 代码，构建属于自己的游戏测试，从而基于原版我的世界基岩版实现一些原来所不能实现的功能！</p>
<p>目前Mojang官方已经提供了一定数量的<a href="https://learn.microsoft.com/zh-cn/minecraft/creator/scriptapi/" target="_blank" rel="noopener noreferrer">API<ExternalLinkIcon/></a>，已经足够我们实现一些有意思的事情。</p>
<h3 id="🚃开始编写脚本开始生成空岛吧" tabindex="-1"><a class="header-anchor" href="#🚃开始编写脚本开始生成空岛吧" aria-hidden="true">#</a> 🚃开始编写脚本开始生成空岛吧！</h3>
<p>首先我们要在游戏中添加一个名为<code v-pre>IslandData</code>的计分板，<strong>并且添加一个名为<code v-pre>num</code>的虚拟对象并将其的值设定为1</strong>！</p>
<p>这里的<code v-pre>IslandData</code>计分板是用于存储空岛相关数据的一个积分板，其中<code v-pre>num</code>为当前空岛的数量。</p>
<p>然后这里为了方便后续的编写，我自定义了几个函数。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">//一些自定义函数</span>

<span class="token doc-comment comment">/**
 * 将Msg消息广播至整个游戏
 * <span class="token keyword">@param</span> <span class="token class-name"><span class="token punctuation">{</span>string<span class="token punctuation">}</span></span> <span class="token parameter">Msg</span>
 */</span>
<span class="token keyword">function</span> <span class="token function">Broadcast</span><span class="token punctuation">(</span><span class="token parameter">Msg</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    world<span class="token punctuation">.</span><span class="token function">getDimension</span><span class="token punctuation">(</span><span class="token string">"overworld"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">runCommandAsync</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">tellraw @a {\"rawtext\":[{\"text\":\"</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>Msg<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">\"}]}</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>

<span class="token doc-comment comment">/**
 * 将Msg消息发送至名为PlayerName的玩家
 * <span class="token keyword">@param</span> <span class="token class-name"><span class="token punctuation">{</span>string<span class="token punctuation">}</span></span> <span class="token parameter">Msg</span>
 * <span class="token keyword">@param</span> <span class="token class-name"><span class="token punctuation">{</span>string<span class="token punctuation">}</span></span> <span class="token parameter">PlayerName</span>
 */</span>
<span class="token keyword">function</span> <span class="token function">Tell</span><span class="token punctuation">(</span><span class="token parameter">Msg<span class="token punctuation">,</span>PlayerName</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    world<span class="token punctuation">.</span><span class="token function">getDimension</span><span class="token punctuation">(</span><span class="token string">"overworld"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">runCommandAsync</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">tellraw @a[name=</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>PlayerName<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">] {\"rawtext\":[{\"text\":\"</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>Msg<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">\"}]}</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>

<span class="token doc-comment comment">/**
 * 运行指令
 * <span class="token keyword">@param</span> <span class="token class-name"><span class="token punctuation">{</span>string<span class="token punctuation">}</span></span> <span class="token parameter">Cmd</span>
 */</span>
<span class="token keyword">function</span> <span class="token function">RunCmd</span><span class="token punctuation">(</span><span class="token parameter">Cmd</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    world<span class="token punctuation">.</span><span class="token function">getDimension</span><span class="token punctuation">(</span><span class="token string">"overworld"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">runCommandAsync</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>Cmd<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我这里生成的空岛是以坐标(cX,cY,cZ)为圆心，空岛按照一个个同心圆排列，每个空岛在该圆上的距离相等，从而最大限度的利用了空间。</p>
<p>以下的脚本我基本注释已经做的很清楚了，请自行查看。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">//定义一些常数</span>
<span class="token keyword">const</span> <span class="token constant">R</span> <span class="token operator">=</span> <span class="token number">100</span><span class="token punctuation">;</span>  <span class="token comment">//空岛间距/初始半径</span>
<span class="token keyword">const</span> <span class="token constant">CX</span> <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token constant">CY</span> <span class="token operator">=</span> <span class="token number">50</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token constant">CZ</span> <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>

<span class="token comment">//自定义函数</span>
<span class="token keyword">function</span> <span class="token function">CaculatePos</span><span class="token punctuation">(</span><span class="token parameter">playerName<span class="token punctuation">,</span>cX<span class="token punctuation">,</span>cY<span class="token punctuation">,</span>cZ</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">//这里首先取得IslandData计分板下所有计分项名称</span>
    <span class="token keyword">let</span> Participants <span class="token operator">=</span> world<span class="token punctuation">.</span>scoreboard<span class="token punctuation">.</span><span class="token function">getObjective</span><span class="token punctuation">(</span><span class="token string">"IslandData"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">getParticipants</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token comment">//这里使用一个循环遍历所有计分项</span>
    <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">let</span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i <span class="token operator">&lt;</span> Participants<span class="token punctuation">.</span>length<span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token comment">//直到计分项名称为num时才执行if里的语句</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>Participants<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span>displayName <span class="token operator">==</span> <span class="token string">"num"</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token comment">//读取计分项num的值，并赋值给变量num</span>
            <span class="token keyword">let</span> num <span class="token operator">=</span> world<span class="token punctuation">.</span>scoreboard<span class="token punctuation">.</span><span class="token function">getObjective</span><span class="token punctuation">(</span><span class="token string">"IslandData"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">getScore</span><span class="token punctuation">(</span>Participants<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token comment">//赋值变量Allnum r</span>
            <span class="token keyword">let</span> AllNum <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
            <span class="token keyword">let</span> r <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
            <span class="token comment">//这里说判断该空岛应该在第几个圆圈上</span>
            <span class="token keyword">do</span> <span class="token punctuation">{</span>
                r <span class="token operator">=</span> r <span class="token operator">+</span> <span class="token constant">R</span><span class="token punctuation">;</span>
                AllNum <span class="token operator">=</span> <span class="token function">parseInt</span><span class="token punctuation">(</span><span class="token number">2</span> <span class="token operator">*</span> Math<span class="token punctuation">.</span><span class="token constant">PI</span> <span class="token operator">*</span> r <span class="token operator">/</span> <span class="token constant">R</span><span class="token punctuation">)</span> <span class="token operator">+</span> AllNum<span class="token punctuation">;</span>
                <span class="token comment">//调试语句（25-27），可以删掉</span>
                <span class="token keyword">if</span> <span class="token punctuation">(</span>num <span class="token operator">&lt;=</span> AllNum<span class="token punctuation">)</span><span class="token punctuation">{</span>
                    <span class="token function">Broadcast</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">§7AllNum：</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>AllNum<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> 此时的半径：</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>r<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
                <span class="token punctuation">}</span>
            <span class="token punctuation">}</span> <span class="token keyword">while</span> <span class="token punctuation">(</span>num <span class="token operator">></span> AllNum<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token comment">//计算该空岛在本圆圈上的第几个位置上</span>
            <span class="token keyword">let</span> pos <span class="token operator">=</span> <span class="token function">parseInt</span><span class="token punctuation">(</span><span class="token number">2</span> <span class="token operator">*</span> Math<span class="token punctuation">.</span><span class="token constant">PI</span> <span class="token operator">*</span> r <span class="token operator">/</span> <span class="token constant">R</span><span class="token punctuation">)</span> <span class="token operator">-</span> AllNum <span class="token operator">+</span> num
            <span class="token comment">//根据位置计算相应的X,Z坐标</span>
            <span class="token keyword">let</span> posX <span class="token operator">=</span> <span class="token function">parseInt</span><span class="token punctuation">(</span>Math<span class="token punctuation">.</span><span class="token function">cos</span><span class="token punctuation">(</span>pos <span class="token operator">*</span> <span class="token number">2</span> <span class="token operator">*</span> Math<span class="token punctuation">.</span><span class="token constant">PI</span> <span class="token operator">/</span> <span class="token punctuation">(</span><span class="token function">parseInt</span><span class="token punctuation">(</span><span class="token number">2</span> <span class="token operator">*</span> Math<span class="token punctuation">.</span><span class="token constant">PI</span> <span class="token operator">*</span> r <span class="token operator">/</span> <span class="token constant">R</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">*</span> r<span class="token punctuation">)</span> <span class="token operator">+</span> cX<span class="token punctuation">;</span>
            <span class="token keyword">let</span> posZ <span class="token operator">=</span> <span class="token operator">-</span><span class="token function">parseInt</span><span class="token punctuation">(</span>Math<span class="token punctuation">.</span><span class="token function">sin</span><span class="token punctuation">(</span>pos <span class="token operator">*</span> <span class="token number">2</span> <span class="token operator">*</span> Math<span class="token punctuation">.</span><span class="token constant">PI</span> <span class="token operator">/</span> <span class="token punctuation">(</span><span class="token function">parseInt</span><span class="token punctuation">(</span><span class="token number">2</span> <span class="token operator">*</span> Math<span class="token punctuation">.</span><span class="token constant">PI</span> <span class="token operator">*</span> r <span class="token operator">/</span> <span class="token constant">R</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">*</span> r<span class="token punctuation">)</span> <span class="token operator">+</span> cZ<span class="token punctuation">;</span>
            <span class="token comment">//调试语句（35），可以删掉</span>
            <span class="token function">Broadcast</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">§7num的值为：</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>num<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> pos的值为：</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>pos<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> posX的值为：</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>posX<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> posZ的值为：</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>posZ<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token comment">//底下的语句就可以按照自己的需求进行更改了，毕竟XZ坐标已经算出来了，我这里的仅供参考</span>
            <span class="token comment">//这里是加载名为island1的结构至计算的坐标</span>
            <span class="token function">RunCmd</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">structure load mystructure:island1 </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>posX<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>cY<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>posZ<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token comment">//然后把玩家传送过去</span>
            <span class="token function">RunCmd</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">tp @a[name=</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>playerName<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">] </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>posX<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>cY <span class="token operator">+</span> <span class="token number">15</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>posZ<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token comment">//最后给空岛数量加一</span>
            <span class="token function">RunCmd</span><span class="token punctuation">(</span><span class="token string">"scoreboard players add num IslandData 1"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token comment">//结束整个循环</span>
            <span class="token keyword">break</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>至此，空岛生成就结束了，你可以按照自己的需求更改相应的脚本语段，从而实现更多有意思的功能！</p>
</div></template>


